import type { Apartment, City } from "@/types"

export const germanCities: City[] = [
  { name: "Berlin", state: "Berlin", coordinates: [52.52, 13.405] },
  { name: "Munich", state: "Bavaria", coordinates: [48.1351, 11.582] },
  { name: "Hamburg", state: "Hamburg", coordinates: [53.5511, 9.9937] },
  { name: "Cologne", state: "North Rhine-Westphalia", coordinates: [50.9375, 6.9603] },
  { name: "Frankfurt", state: "Hesse", coordinates: [50.1109, 8.6821] },
  { name: "Stuttgart", state: "Baden-Württemberg", coordinates: [48.7758, 9.1829] },
  { name: "Düsseldorf", state: "North Rhine-Westphalia", coordinates: [51.2277, 6.7735] },
  { name: "Leipzig", state: "Saxony", coordinates: [51.3397, 12.3731] },
  { name: "Dortmund", state: "North Rhine-Westphalia", coordinates: [51.5136, 7.4653] },
  { name: "Essen", state: "North Rhine-Westphalia", coordinates: [51.4556, 7.0116] },
]

export const mockApartments: Apartment[] = [
  {
    id: "1",
    title: "Modern Apartment in Mitte",
    description: "Beautiful modern apartment in the heart of Berlin with high ceilings and large windows.",
    price: 1200,
    size: 65,
    rooms: 2,
    city: "Berlin",
    address: "Unter den Linden 15, 10117 Berlin",
    coordinates: [52.517, 13.3888],
    images: ["/modern-apartment.png"],
    features: ["Balcony", "Elevator", "Parking", "Pet-friendly"],
    neighborhood: "Mitte",
    lifestyleTags: ["central", "cultural", "transport"],
    available: true,
    createdAt: Date.now() - 86400000,
  },
  {
    id: "2",
    title: "Cozy Studio in Schwabing",
    description: "Charming studio apartment in Munich's trendy Schwabing district.",
    price: 950,
    size: 35,
    rooms: 1,
    city: "Munich",
    address: "Leopoldstraße 45, 80802 Munich",
    coordinates: [48.15, 11.58],
    images: ["/cozy-studio-apartment.png"],
    features: ["Furnished", "Internet included", "Near university"],
    neighborhood: "Schwabing",
    lifestyleTags: ["nightlife", "cultural", "transport"],
    available: true,
    createdAt: Date.now() - 172800000,
  },
  {
    id: "3",
    title: "Family Home in Altona",
    description: "Spacious family apartment with garden access in Hamburg's Altona district.",
    price: 1800,
    size: 120,
    rooms: 4,
    city: "Hamburg",
    address: "Große Bergstraße 20, 22767 Hamburg",
    coordinates: [53.55, 9.93],
    images: ["/family-apartment-garden.png"],
    features: ["Garden", "Parking", "Storage", "Playground nearby"],
    neighborhood: "Altona",
    lifestyleTags: ["familyFriendly", "green", "quiet"],
    available: true,
    createdAt: Date.now() - 259200000,
  },
  {
    id: "4",
    title: "Luxury Penthouse in Düsseldorf",
    description: "Exclusive penthouse with panoramic city views and premium amenities.",
    price: 2500,
    size: 95,
    rooms: 3,
    city: "Düsseldorf",
    address: "Königsallee 100, 40212 Düsseldorf",
    coordinates: [51.225, 6.78],
    images: ["/luxury-penthouse-city-view.png"],
    features: ["Terrace", "Concierge", "Gym", "Premium location"],
    neighborhood: "Stadtmitte",
    lifestyleTags: ["central", "shopping", "transport"],
    available: false,
    createdAt: Date.now() - 345600000,
  },
  {
    id: "5",
    title: "Student Flat in Frankfurt",
    description: "Affordable apartment perfect for students near Goethe University.",
    price: 750,
    size: 28,
    rooms: 1,
    city: "Frankfurt",
    address: "Bockenheimer Landstraße 85, 60325 Frankfurt",
    coordinates: [50.12, 8.67],
    images: ["/student-apartment-near-university.png"],
    features: ["Furnished", "Internet", "Laundry", "Study room"],
    neighborhood: "Bockenheim",
    lifestyleTags: ["transport", "cultural", "central"],
    available: true,
    createdAt: Date.now() - 432000000,
  },
]

export const lifestyleOptions = [
  "familyFriendly",
  "nightlife",
  "quiet",
  "central",
  "green",
  "transport",
  "shopping",
  "cultural",
]
